export const LOAD_NODES = "LOAD_NODES";
export const LOAD_NODES_SUCCESS = "LOAD_NODES_SUCCESS";
export const SET_SELECTED_BY_IDS_REST_UNSELECTED = "SET_SELECTED_BY_IDS_REST_UNSELECTED";
export const SET_SELECT_BY_ID = "SET_SELECT_BY_ID";
