export const LOAD_ITEMS = "LOAD_ITEMS ";
export const LOAD_ITEMS_SUCCESS = "LOAD_ITEMS_SUCCESS";
export const CREATE_ITEM = "CREATE_ITEM";
export const CREATE_ITEM_SUCCESS = "CREATE_ITEM_SUCCESS";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
